SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS orquestraMusico;
DROP TABLE IF EXISTS musicoFuncao;
DROP TABLE IF EXISTS apresentacao;
DROP TABLE IF EXISTS sinfonias;
DROP TABLE IF EXISTS funcao;
DROP TABLE IF EXISTS instrumentos;
DROP TABLE IF EXISTS orquestras;
DROP TABLE IF EXISTS musicos;

SET FOREIGN_KEY_CHECKS = 1;

DROP DATABASE conservatorio;
